modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="escape_velocity"
version="1.0.0"
displayName="Escape Velocity"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Acidpop"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.escape_velocity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.escape_velocity]]
    modId="nexus_compiled_mods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.escape_velocity]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration